From now on the autograder will be refered to as the hacksaw. I updated the gitignore so it would no longer track the models or files created during learning and inference.

diff --git a/hacksaw b/hacksaw
--- a/hacksaw
+++ b/hacksaw
@@ -5,6 +5,9 @@
 # hayesall@indiana.edu
 # Last updated: 4/20/2017
 
+# Sample call:
+# $ bash autograder.sh [JAR-FILE]
+
 RED='\033[0;31m'
 LIGHTGREEN='\033[1;32m'
 YELLOW='\033[1;33m'
@@ -13,14 +16,6 @@ NC='\033[0m'
 BOLD='\e[1m'
 ITAL='\e[3m'
 UNDL='\e[4m'
-
-# It will be pretty straightforward to establish that testing is consistent. Training is more difficult.
-
-# java -jar v1-0.jar -l -train datasets/Father/train/ -target father -trees 25 > trainlog.txt
-# java -jar v1-0.jar -i -model datasets/Father/train/models/ -test datasets/Father/test/ -target father -trees 25 > testlog.txt
-
-# Sample call:
-# $ bash autograder.sh [JAR-FILE]
 
 NUMBEROFERRORS=0
 
@@ -49,8 +44,6 @@ else
     exit 2
 fi
 
-# Father dataset:
-
 NAMES=(
     "RDN-Boost"
     "RDN-Boost with -noBoost"
@@ -62,6 +55,7 @@ NAMES=(
 )
 
 ECHOS=(
+    # Father
     "Testing default functionality with boosted regression trees..."
     "Testing with boosting disabled (-noBoost)..."
     "Testing soft margin with alpha(0.5) and beta(-2)..."
@@ -72,6 +66,7 @@ ECHOS=(
 )
 
 TRAINS=(
+    # Father
     "java -jar $JAR -l -train datasets/Father/train/ -target father -trees 25"
     "java -jar $JAR -l -noBoost -train datasets/Father/train -target father"
     "java -jar $JAR -l -softm -alpha 0.5 -beta -2 -train datasets/Father/train -target father -trees 25"
@@ -82,6 +77,7 @@ TRAINS=(
 )
 
 TESTS=(
+    # Father
     "java -jar $JAR -i -model datasets/Father/train/models -test datasets/Father/test/ -target father -trees 25"
     "java -jar $JAR -i -model datasets/Father/train/models -test datasets/Father/test/ -target father"
     "java -jar $JAR -i -model datasets/Father/train/models -test datasets/Father/test/ -target father -trees 25"
@@ -92,6 +88,7 @@ TESTS=(
 )
 
 COMPARES=(
+    # Father
     "python compare.py datasets/Father/test/results_father.db static/Father/results_rdn.db"
     "python compare.py datasets/Father/test/results_father.db static/Father/results_rdn_noboost.db"
     "python compare.py datasets/Father/test/results_father.db static/Father/results_softmA0.5B-2.db"
@@ -101,42 +98,32 @@ COMPARES=(
     "python compare.py datasets/Father/test/results_father.db static/Father/results_regression.db"
 )
 
-for ((i=0; i<${#ECHOS[*]}; i++)); do
-    printf "\n"
-    echo ${ECHOS[i]}
-    ${TRAINS[i]} > trainlog.txt
-    if [[ "$?" = 0 ]]; then
-	printf " - ${LIGHTGREEN}Training completed without errors.${NC}\n"
-	${TESTS[i]} > testlog.txt
-	if [[ "$?" = 0 ]]; then
-	    printf " - ${LIGHTGREEN}Testing completed without errors.${NC}\n"
-	    ${COMPARES[i]}
-	else
-	    printf " - ${RED}Errors encountered during testing for ${NAMES[i]}.${NC}\n"
-	fi
-    else
-	printf " - ${RED}Errors encountered during training for ${NAMES[i]}.${NC}\n"
-    fi
-done
+EPOCHS=15
+# add an additional parameter to compare.py for changing the sensitivity threshold
 
-exit 0
-
-# RDN-Boost
-echo "Testing default functionality with boosted regression trees..."
-java -jar $JAR -l -train datasets/Father/train/ -target father -trees 25 > trainlog.txt
-if [[ "$?" = 0 ]]; then
-    printf " - ${LIGHTGREEN}Training completed without errors.${NC}\n"
-    java -jar $JAR -i -model datasets/Father/train/models -test datasets/Father/test/ -target father -trees 25 > testlog.txt
-    if [[ "$?" = 0 ]]; then
-	printf " - ${LIGHTGREEN}Testing completed without errors.${NC}\n"
-	python compare.py datasets/Father/test/results_father.db static/Father/results_rdn.db
-    else
-	printf " - ${RED}Errors encountered during testing for RDN-Boost.${NC}\n"
-    fi
-else
-    printf " - ${RED}Errors encountered during training for RDN-Boost.${NC}\n"
+if [[ -e Results.txt ]]; then
+    rm -f Results.txt
 fi
 
+for ((j=0; j<${EPOCHS}; j++)); do
+    for ((i=0; i<${#ECHOS[*]}; i++)); do
+	printf "\n"
+	printf "${LIGHTBLUE}${ECHOS[i]}${NC}\n"
+	${TRAINS[i]} > trainlog.txt
+	if [[ "$?" = 0 ]]; then
+	    printf " - ${LIGHTGREEN}Training completed without errors.${NC}\n"
+	    ${TESTS[i]} > testlog.txt
+	    if [[ "$?" = 0 ]]; then
+		printf " - ${LIGHTGREEN}Testing completed without errors.${NC}\n"
+		${COMPARES[i]} >> Results.txt
+	    else
+		printf " - ${RED}Errors encountered during testing for ${NAMES[i]}.${NC}\n"
+	    fi
+	else
+	    printf " - ${RED}Errors encountered during training for ${NAMES[i]}.${NC}\n"
+	fi
+    done
+done
 exit 0
 
 #if [[ -e datasets/Father/test/results_father.db ]]; then
